export default defineAppConfig({
  appName: "Global Wire",
  categoriesList: [
    {value: "general", label: "General", icon: 'i-streamline-plump:news-paper' },
    {value: "business",label: "Business", icon: 'i-material-symbols:business-center-outline'},
    {value: "entertainment", label: "Entertainment", icon: 'i-streamline-pixel:entertainment-events-hobbies-popcorn'},
    {value: "health", label: "Health", icon: 'i-ix:health'},
    {value: "science", label: "Science", icon: 'i-pixel:science'},
    {value: "sports", label: "Sports", icon: "i-material-symbols:sports-tennis"},
    {value: "technology", label: "Technology", icon: "i-hugeicons:nano-technology"},
  ],
  sortByOptions: {
    Relevancy: "relevancy",
    Popularity: "popularity",
    "Published At": "publishedAt",
  },
  countriesList: {
    "United States": "us",
    "United Arab Emirates": "ae",
    Argentina: "ar",
    Austria: "at",
    Australia: "au",
    Belgium: "be",
    Bulgaria: "bg",
    Brazil: "br",
    Canada: "ca",
    Switzerland: "ch",
    China: "cn",
    Colombia: "co",
    Cuba: "cu",
    "Czech Republic": "cz",
    Germany: "de",
    Egypt: "eg",
    France: "fr",
    "United Kingdom": "gb",
    Greece: "gr",
    "Hong Kong": "hk",
    Hungary: "hu",
    Indonesia: "id",
    Ireland: "ie",
    Israel: "il",
    India: "in",
    Italy: "it",
    Japan: "jp",
    "South Korea": "kr",
    Lithuania: "lt",
    Latvia: "lv",
    Morocco: "ma",
    Mexico: "mx",
    Malaysia: "my",
    Nigeria: "ng",
    Netherlands: "nl",
    Norway: "no",
    "New Zealand": "nz",
    Philippines: "ph",
    Poland: "pl",
    Portugal: "pt",
    Romania: "ro",
    Serbia: "rs",
    Russia: "ru",
    "Saudi Arabia": "sa",
    Sweden: "se",
    Singapore: "sg",
    Slovenia: "si",
    Slovakia: "sk",
    Thailand: "th",
    Turkey: "tr",
    Taiwan: "tw",
    Ukraine: "ua",
    Venezuela: "ve",
    "South Africa": "za",
  },
  routeNames: {
    homepage: "/",
    sources: "/sources",
    search: "/search",
    categories: "/categories",
  }, 
  endpointBases: {
    HEADLINES: "/api/news/top-headlines",
    SOURCES: "/api/news/top-headlines/sources",
    EVERYTHING: "/api/news/everything",
  },
  portfolioLink: "https://mahmoudfarargy.vercel.app",
})
